---
project_name: rproxy

release:
  github:
    owner: ccojocar
    name: rproxy

builds:
  - main : ./
    binary: rproxy
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags: -X main.Version={{.Version}} -X main.GitTag={{.Tag}} -X main.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0
