name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
      - name: Run Unit Tests
        uses: cedrickring/golang-action@1.6.0
        with:
          args: make test
      - name: Run Integration Tests
        uses: cedrickring/golang-action@1.6.0
        with:
          args: make integration-test
